<a href="https://colab.research.google.com/github/Nithilan98/DataScience_Tasks/blob/main/Task_02_100_Numpy_Exercises_Nithilaselvan_D18_DataScienceTask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__) # np.__version__, shows numpy version
np.show_config()    # np.show_config(), shows the numpy configuration

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:

a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
a = np.array([10,20,30])
print("Size of the array:",a.size)
print("Memory size of one array element in bytes:",a.itemsize)
print("Memory size of the array:",(a.size*a.itemsize),"bytes")

Size of the array: 3
Memory size of one array element in bytes: 8
Memory size of the array: 24 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
!python -c "import numpy as np; np.info(np.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
n = np.zeros(10)
n[4]=1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
a =np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
print("Normal array")
print(a)
print("Reversed vecotor")
print(a[::-1])

Normal array
[1 2 3 4 5 6 7 8]
Reversed vecotor
[8 7 6 5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
a= np.random.random((3,3,3))
print(a)

[[[0.05305754 0.14467215 0.93336841]
  [0.86353676 0.70594338 0.00436052]
  [0.28322087 0.63553606 0.93773049]]

 [[0.38498003 0.45201985 0.60763055]
  [0.58921841 0.69120518 0.8586416 ]
  [0.05135242 0.49666403 0.63357428]]

 [[0.19815208 0.75679785 0.49080975]
  [0.28795659 0.54169674 0.71631108]
  [0.48688999 0.08186954 0.91220465]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
a = np.random.random((10,10))
#print("The 10 x 10 array : \n",a)
print("Minumum value: ", a.min())
print("Maximum value: ", a.max())

Minumum value:  0.021038495776062538
Maximum value:  0.9570096781572249


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
a=np.random.random(30)
print("Mean Value: ", a.mean())

Mean Value:  0.4667300168723911


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
a=np.ones((5,5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
a=np.ones((5,5))
a=np.pad(a,pad_width=1,mode="constant",  constant_values=0)
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)


nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
#diag method to print given value to diagonal format.
#k=-1 means below the digonal its means 1 step back if we put the k=1 it will print the one step above the diagonal.
#a=np.diag(1+np.arange(4),k =-1) 
#a
a=np.diag([1,2,3,4],k =-1) 
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
#19)checkerboard pattern answer
a= np.zeros ((8,8), dtype=int)
a[1::2, ::2]= 1
a[::2, 1::2] = 1
print (a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
a = np.array([[0,1],[1,0]])
a = np.tile(a,(4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
x = (x-(x.max()))/((x.max())-(x.min()))
print(x)

[[-0.42706055 -0.88615619 -0.68677899 -0.25117444 -0.69116165]
 [-0.81144893 -0.69242151 -0.83034524 -0.10293056  0.        ]
 [-0.97665911 -0.59679086 -0.1355978  -0.49039348 -0.00575245]
 [-0.53593376 -0.27920281 -0.98134026 -0.37830692 -0.70870343]
 [-0.93907622 -0.45309883 -0.43642627 -1.         -0.26239728]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
a = np.dot(np.ones((5,3)),np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
a = np.arange(11)
a[(3<a) & (a<8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z=np.arange(10)
print(z**z)
print(2 << z >> 2)
print(z <- z)
print(1j*z)
print(z/1/1)
print((z<z)>z)


[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[False False False False False False False False False False]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0)/np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
a = np.random.uniform(-5,+5,10)
print(a)
print(np.copysign(np.ceil(np.abs(a)), a))

[-4.26644095  1.27701613 -0.86251187  1.10945404  0.24629106 -3.02775544
 -1.11375715 -0.63866865  2.62867961  4.6138374 ]
[-5.  2. -1.  2.  1. -4. -2. -1.  3.  5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a = np.random.randint(0,5,5)
b = np.random.randint(0,5,5)
print(a)
print(b)
print(np.intersect1d(a,b))

[1 1 2 4 1]
[2 4 2 2 4]
[2 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all="ignore")
a = np.ones(1)/0
np.errstate(all="ignore")
a

array([inf])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today')-np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today')+np.timedelta64(1)
print("Yesterday: ", yesterday)
print("Today: ",today)
print("Tomorrow: ",tomorrow)


Yesterday:  2022-02-04
Today:  2022-02-05
Tomorrow:  2022-02-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*3
B = np.ones(3)*2
print(A)
print(B)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

[3. 3. 3.]
[2. 2. 2.]


array([-7.5, -7.5, -7.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.uniform(1,5,5)
print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[4.99332897 2.72513175 2.9998625  3.58897503 1.1371295 ]
[4. 2. 2. 3. 1.]
[4. 2. 2. 3. 1.]
[4. 2. 2. 3. 1.]
[4 2 2 3 1]
[4. 2. 2. 3. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
a = np.zeros((5,5))
a+=np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
a= np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
a= np.linspace(0,1,12,endpoint=True)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
a = np.random.random(10)
print("Random Vector: \n",a)
a.sort()
print("Sorted Vecotr: \n",a)

Random Vector: 
 [0.25699004 0.29869809 0.17508159 0.53754657 0.54766796 0.29514876
 0.22856368 0.94444032 0.03122303 0.32689052]
Sorted Vecotr: 
 [0.03122303 0.17508159 0.22856368 0.25699004 0.29514876 0.29869809
 0.32689052 0.53754657 0.54766796 0.94444032]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
a=np.arange(5)
print(a)
np.add.reduce(a)

[0 1 2 3 4]


10

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.ones(5)
B = np.ones(5)
#using np.allclose 
print(np.allclose(A,B))
#using np.array_equal
print(np.array_equal(A,B))

True
True


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
a = np.random.random((10,2))
X,Y = a[:,0], a[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.52350602 0.99745991 0.97273615 0.09421623 0.73109144 0.95785095
 0.59825671 0.3693346  0.51243509 1.16783986]
[0.36942776 1.24212697 0.7702655  1.37193629 0.99283965 0.59359413
 1.38729319 1.48373201 0.57006223 0.56688959]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
a = np.random.random(10)
print(a)
a[a.argmax()]=0
print("\nResult: \n")
print(a)

[0.78040751 0.26208686 0.76310087 0.13045467 0.83330034 0.76612762
 0.05334379 0.57416962 0.61230826 0.58691541]

Result: 

[0.78040751 0.26208686 0.76310087 0.13045467 0.         0.76612762
 0.05334379 0.57416962 0.61230826 0.58691541]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
a = np.zeros((10,10), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(a)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(10)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


33961.93294480225


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8,np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
a = np.arange(1005)
np.set_printoptions(threshold=np.inf)
print(a)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
a = np.arange(100)
print(a)
b = np.random.uniform(0,100)
print(b)
index = (np.abs(a-b)).argmin()
print(a[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
25.828652840162214
26


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
a = np.zeros(10, [("position", [ ("x", float, 1),("y", float, 1)]),("color",[ ("r", float, 1),("g", float, 1),("b", float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
a = np.random.random((100,2))
X,Y = np.atleast_2d(a[:,0]), np.atleast_2d(a[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.30514008 0.55070083 0.74978461 0.58939395 0.66472116
  0.87695218 0.84899633 0.85432769 0.21650247 0.1676097  0.56587306
  0.92509621 0.15777991 0.68294177 0.49793356 0.31989794 0.14603111
  0.37013761 0.32579571 0.64553624 0.43991009 0.64977944 0.37823662
  0.75497299 0.13021027 0.68051773 0.57376691 0.78152568 0.66767324
  0.68212576 0.40028247 0.89164193 0.32286709 0.61901348 0.87677191
  0.62173349 0.22880271 0.3583576  0.26402646 0.08265734 0.64376933
  0.65758571 0.53927175 0.18527677 0.98325652 0.26701427 0.87101298
  0.82055505 0.05774562 0.67249339 0.62356417 0.88681913 0.27169702
  0.66953608 0.75311011 0.63412387 0.73039515 0.21573873 0.74770972
  0.69571695 0.61446453 0.59760737 0.80566444 0.35754918 0.23093097
  0.22049012 0.51732497 0.18300067 0.47433857 0.61597285 0.1591906
  0.74947248 0.64116327 0.34563006 0.67449552 0.1719207  0.44600481
  0.94214773 0.80149278 0.68008104 0.4393794  0.23319077 0.46155186
  0.66005145 0.44318862 0.20012607 0.40784463 0.5

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
a = np.arange(10,dtype=np.int32)
print(a)
a = a.astype(np.float32, copy=False)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')

a=np.genfromtxt(s,delimiter=",",dtype=np.int)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
a=np.arange(9).reshape(3,3)
a
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n=10
p = 9
a= np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False),7)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0. 0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 0. 7. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 7. 0. 7. 0. 0. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0. 0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 0. 0. 7. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
a = np.random.rand(5, 10)
#print(a.mean(axis=1, keepdims=True))
#print(a)
x = a- a.mean(axis=1, keepdims=True)
print(x)

[[0.4074704 ]
 [0.46263937]
 [0.34567147]
 [0.49917863]
 [0.62946552]]
[[0.60756721 0.71231855 0.30667923 0.24907004 0.44785244 0.0633661
  0.00953873 0.56756021 0.40083444 0.70991708]
 [0.92499415 0.56966333 0.07947472 0.41717486 0.77392154 0.66538148
  0.73234424 0.18888225 0.18708759 0.0874695 ]
 [0.28264624 0.15257745 0.06987621 0.13897812 0.27437052 0.59220212
  0.46248391 0.88716553 0.20569999 0.39071457]
 [0.3248654  0.19626444 0.62943518 0.87929884 0.30714655 0.78899881
  0.2534464  0.80266431 0.74623065 0.06343575]
 [0.70741114 0.00966733 0.32960669 0.82917479 0.60815004 0.93283652
  0.42648793 0.6227489  0.99091412 0.83765773]]
[[ 0.20009681  0.30484815 -0.10079117 -0.15840036  0.04038203 -0.34410431
  -0.39793168  0.16008981 -0.00663596  0.30244668]
 [ 0.46235479  0.10702397 -0.38316465 -0.0454645   0.31128218  0.20274212
   0.26970487 -0.27375711 -0.27555178 -0.37516987]
 [-0.06302522 -0.19309401 -0.27579525 -0.20669335 -0.07130094  0.24653065
   0.11681244  0.54149406 -0.1

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
a= np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,2].argsort()])

[[2 0 6]
 [5 5 4]
 [5 0 0]]
[[5 0 0]
 [5 5 4]
 [2 0 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
a = np.random.randint(0,3,(3,10))
print(a)
print((~a.any(axis=0)).any())



[[0 1 0 1 1 0 1 2 0 1]
 [1 2 1 1 1 2 1 1 2 0]
 [2 2 0 2 1 0 1 1 2 0]]
False


In [ ]:
Z = np.random.randint(0,3,(3,10)).astype(float)
Z[:,0] = np.nan
G = np.isnan(Z)
print((G.all(axis=0)).any())


True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
a = np.random.uniform(0,5,10)
print(a)
v = 1
f = a.flat[np.abs(a-v).argmin()]
print(f)

[0.1190151  4.34693923 0.68556995 3.33106121 0.30910765 3.85491522
 1.93365342 2.75252389 2.46106917 0.98910226]
0.9891022587258397


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
it = np.nditer([A,B,None])
for x,y,z in it:
  z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class Name(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None:
          return
        self.info = getattr(obj, 'name', "no name")

Z = Name(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
a= np.ones(10)
I = np.random.randint(0,len(a),20)
a += np.bincount(I, minlength=len(a))
print(a)



[1. 5. 4. 2. 4. 4. 3. 3. 2. 2.]


In [ ]:
np.add.at(a, I, 1)
print(a)

[1. 9. 7. 3. 7. 7. 5. 5. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
#inital set:  I=  [1,3,9,3,4,1]   
#weight       x=  [1,2,3,4,5,6]
#maximum size is 9 because 9 is the max number
#Bin:             [0,1,2,3,4,5,6,7,8,9]
#sum of weights:  [0,2,0,2,1,0,0,0,0,1]
#Binvalue:        [0,7,0,6,5,0,0,0,0,3]
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
print(A)
sum = A.sum(axis=(-2,-1))
print("\n sum : \n")
print(sum)

[[[[1 1 3 0]
   [3 3 8 9]
   [7 8 9 2]]

  [[0 2 1 9]
   [7 2 8 8]
   [3 6 5 5]]

  [[7 8 9 5]
   [9 0 6 4]
   [0 9 0 5]]

  [[6 9 0 4]
   [0 8 1 4]
   [8 1 1 4]]]


 [[[1 4 2 2]
   [4 9 3 7]
   [9 7 4 7]]

  [[6 1 6 9]
   [8 4 8 7]
   [0 2 0 2]]

  [[3 6 5 1]
   [0 7 1 6]
   [0 0 3 0]]

  [[6 5 8 1]
   [9 7 6 1]
   [7 6 8 7]]]


 [[[6 2 9 5]
   [9 8 0 0]
   [3 1 4 2]]

  [[8 8 8 4]
   [5 1 7 9]
   [0 1 5 3]]

  [[7 0 9 4]
   [4 6 7 0]
   [3 7 6 0]]

  [[1 9 0 1]
   [8 5 9 7]
   [1 7 9 3]]]]

 sum : 

[[54 56 62 46]
 [59 53 32 71]
 [49 59 53 60]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.48365303 0.58661946 0.36813193 0.56535282 0.60089329 0.5727182
 0.54552272 0.47471018 0.47277591 0.46496846]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
print(np.dot(A,B))
print("\n diaonal of dot product: \n")
d=np.diag(np.dot(A, B))
print(d)

[[63 18 62]
 [57 26 49]
 [81 38 80]]

 diaonal of dot product: 

[63 26 80]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
a = np.array([1,2,3,4,5])
n = np.zeros(len(a) + (len(a)-1)*3)
n[::4]=a
print(n)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))

print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A = np.arange(15).reshape(3,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 5, 10) ( 5, 17) ( 5, 75) ( 5, 98) (10, 17) (10, 54) (10, 55) (11, 13)
 (11, 77) (11, 95) (11, 98) (12, 26) (12, 79) (13, 98) (24, 36) (24, 53)
 (26, 79) (36, 53) (42, 77) (42, 81) (47, 76) (47, 92) (54, 55) (55, 79)
 (55, 97) (75, 98) (76, 92) (77, 81) (77, 95) (79, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = np.arange(20)
print(moving_average(a, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
a = rolling(np.arange(10), 3)
print(a)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
a = np.random.randint(0,2,100)
print (" original: ")
print(a)
print("Negating a boolean: ")
print(np.logical_not(a, out=a))


b = np.random.uniform(-1.0,1.0,10)
print ('original: ')
print (b)
print ('Change the sign of float inplace: ')
print(np.negative(b, out=b))

 original: 
[1 0 1 1 0 0 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 1
 0 1 0 0 1 0 1 0 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 0 1 0 1 1
 1 1 0 0 1 0 0 0 0 1 1 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1]
Negating a boolean: 
[0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 0 0 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 1 1 1 0
 1 0 1 1 0 1 0 1 0 0 0 0 1 1 0 0 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 1 0 1 0 0
 0 0 1 1 0 1 1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0]
original: 
[-0.62096612 -0.21414705 -0.67599746 -0.21478699  0.76728883 -0.23480267
 -0.127298    0.18017889 -0.13818208 -0.85189659]
Change the sign of float inplace: 
[ 0.62096612  0.21414705  0.67599746  0.21478699 -0.76728883  0.23480267
  0.127298   -0.18017889  0.13818208  0.85189659]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 9.67938136  2.82529785  8.13698057  2.03301328  6.43193876 19.36328379
  2.41214375  0.43414573 10.00557949  0.43743825]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[10.14856799  6.19124241  1.76479769 12.15275177  2.10434476  2.79439678
  20.26057853 13.54527319  1.17814982  7.9177926 ]
 [ 8.24477075  4.86660549  2.74892993  9.95008623  0.89585575  0.55824892
  17.76721661 11.12549511  0.85003974  7.32562596]
 [ 2.49945383  6.9904157   0.1885418   4.59917593  4.93073261  0.47529972
  14.71274562  8.93120812  4.27693591  1.91875312]
 [ 4.01467946  4.27173237  2.66929555  5.55325576  2.62548451  2.21791195
  13.94203388  7.70861708  1.46602561  4.62117919]
 [ 7.70262561  4.19096285  0.93644922  6.29406044 12.93751812  8.44490669
   4.49062562  0.44843661  8.9404958   3.79675995]
 [ 7.2552475  13.79482752  8.26265405  3.80852316 15.9622912   0.75593564
  11.86237786  7.87473504 15.14333136  9.15273693]
 [ 5.04817611  7.61373879  1.9564931   2.88917828 11.8136338   3.85588706
   9.11784795  4.24046328  9.54797233  3.90297617]
 [ 4.40692606 14.78723636  8.78020165  0.72258938 13.80194314  3.17779786
  14.87025037 10.66937461 13.9837891   7.68169396]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 8 3 4 9 1 8 5 6 3]
 [7 3 9 5 9 5 5 0 7 5]
 [7 7 6 6 7 8 8 9 2 9]
 [0 5 2 5 1 7 8 7 9 1]
 [4 2 1 0 5 1 5 1 5 3]
 [3 6 4 8 0 0 3 9 9 0]
 [0 7 6 3 9 3 4 4 8 2]
 [6 2 7 7 1 2 4 2 4 1]
 [7 0 5 1 7 6 8 9 8 9]
 [1 6 4 7 2 0 4 4 8 6]]
[[0 0 0 0 0]
 [0 2 8 3 4]
 [0 7 3 9 5]
 [0 7 7 6 6]
 [0 0 5 2 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
a = np.arange(1,15,dtype=int)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(a, 4)
print ('original: ')
print (a)
print ('after strides: ')
print(R)

original: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
after strides: 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
a = np.random.randint(0,10,50)
print (a)
print(np.bincount(a).argmax())

[8 5 4 2 7 5 3 9 4 2 3 9 8 1 9 0 0 0 7 4 6 3 5 1 9 8 9 6 4 3 6 1 1 9 6 3 3
 5 1 7 2 1 1 5 5 9 4 2 2 2]
1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 3 0]
   [4 3 4]
   [2 4 1]]

  [[3 0 0]
   [3 4 3]
   [4 1 2]]

  [[0 0 1]
   [4 3 0]
   [1 2 1]]

  [[0 1 2]
   [3 0 3]
   [2 1 4]]

  [[1 2 2]
   [0 3 2]
   [1 4 4]]

  [[2 2 2]
   [3 2 0]
   [4 4 4]]

  [[2 2 1]
   [2 0 1]
   [4 4 4]]

  [[2 1 0]
   [0 1 1]
   [4 4 3]]]


 [[[4 3 4]
   [2 4 1]
   [3 0 1]]

  [[3 4 3]
   [4 1 2]
   [0 1 4]]

  [[4 3 0]
   [1 2 1]
   [1 4 4]]

  [[3 0 3]
   [2 1 4]
   [4 4 0]]

  [[0 3 2]
   [1 4 4]
   [4 0 0]]

  [[3 2 0]
   [4 4 4]
   [0 0 1]]

  [[2 0 1]
   [4 4 4]
   [0 1 4]]

  [[0 1 1]
   [4 4 3]
   [1 4 4]]]


 [[[2 4 1]
   [3 0 1]
   [3 2 1]]

  [[4 1 2]
   [0 1 4]
   [2 1 0]]

  [[1 2 1]
   [1 4 4]
   [1 0 4]]

  [[2 1 4]
   [4 4 0]
   [0 4 3]]

  [[1 4 4]
   [4 0 0]
   [4 3 1]]

  [[4 4 4]
   [0 0 1]
   [3 1 1]]

  [[4 4 4]
   [0 1 4]
   [1 1 3]]

  [[4 4 3]
   [1 4 4]
   [1 3 4]]]


 [[[3 0 1]
   [3 2 1]
   [0 4 2]]

  [[0 1 4]
   [2 1 0]
   [4 2 4]]

  [[1 4 4]
   [1 0 4]
   [2 4 4]]

  [[4 4 0]
   [0 4 3]
   [4 4 3]]

  [[4 0 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8  7  6  9 15]
 [ 7  0  1  6 17]
 [ 6  1  3 42  9]
 [ 9  6 42  3  2]
 [15 17  9  2  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
a = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], k), axis=0),
                                       np.arange(0, a.shape[1], k), axis=1)
print(a)
print(S)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])


[9995 9996 9997 9998 9999]
[9998 9999 9997 9995 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [2]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [3]:
a = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(a)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [5]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 4.19 s per loop
1 loop, best of 5: 214 ms per loop
10 loops, best of 5: 177 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [10]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A)
print("\n")
print(B)
print("\n")
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[[3 0 2]
 [3 4 1]
 [1 0 2]
 [2 0 4]
 [0 3 2]
 [1 3 2]
 [0 0 3]
 [3 1 3]]


[[4 0]
 [1 1]]


[1 2 3 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [20]:
Z = np.random.randint(0,5,(10,3))

E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)

U = Z[~E]

print(Z)

print(U)



[[1 3 1]
 [2 1 1]
 [0 1 4]
 [0 2 4]
 [3 3 1]
 [2 3 1]
 [1 1 0]
 [3 3 0]
 [3 4 1]
 [0 0 3]]
[[1 3 1]
 [2 1 1]
 [0 1 4]
 [0 2 4]
 [3 3 1]
 [2 3 1]
 [1 1 0]
 [3 3 0]
 [3 4 1]
 [0 0 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [22]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [13]:
Z = np.random.randint(0,2,(6,3))

T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))

_, i = np.unique(T, return_index=True)

u = Z[i]

print(u)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [19]:
A = np.random.uniform(0,1,10)

B = np.random.uniform(0,1,10)

print(np.einsum('i->', A)) # np.sum(A)
print("\n")
print(np.einsum('i,i->i', A, B)) # A * B
print("\n")
print(np.einsum('i,i', A, B)) # np.inner(A, B)
print("\n")
print(np.einsum('i,j', A, B)) # np.outer(A, B)

5.683181977219969


[0.71978432 0.04774599 0.38639749 0.00991829 0.06476738 0.03640956
 0.42672886 0.10712883 0.71992677 0.00407353]


2.5228810074564105


[[7.19784324e-01 3.22127819e-01 3.54951888e-01 4.48132415e-01
  6.06552447e-02 4.50363374e-01 4.17825621e-01 1.00755369e-01
  6.77835785e-01 5.18970352e-01]
 [1.06686886e-01 4.77459886e-02 5.26111927e-02 6.64224693e-02
  8.99035864e-03 6.67531434e-02 6.19303770e-02 1.49340243e-02
  1.00469248e-01 7.69221129e-02]
 [7.83550848e-01 3.50665495e-01 3.86397485e-01 4.87832983e-01
  6.60287629e-02 4.90261586e-01 4.54841275e-01 1.09681403e-01
  7.37886040e-01 5.64946534e-01]
 [1.59306227e-02 7.12949223e-03 7.85597076e-03 9.91828828e-03
  1.34245188e-03 9.96766497e-03 9.24752331e-03 2.22996766e-03
  1.50021969e-02 1.14861085e-02]
 [7.68582235e-01 3.43966535e-01 3.79015917e-01 4.78513636e-01
  6.47673783e-02 4.80895843e-01 4.46152186e-01 1.07586098e-01
  7.23789788e-01 5.54154043e-01]
 [5.81908535e-02 2.60423742e-02 2.86960310e-02 3.62291965e-

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)

a = 1

x = a*phi*np.cos(phi)

y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths

r = np.zeros_like(x)

r[1:] = np.cumsum(dr) # integrate path

r_int = np.linspace(0, r.max(), 200) # regular spaced path


x_int = np.interp(r_int, r, x) # integrate path

y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [25]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],

[2.0, 0.0, 1.0, 1.0],

[1.5, 2.5, 1.0, 0.0]])

n = 4

M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)

M &= (X.sum(axis=-1) == n)

print(X[M])



[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [26]:
X = np.random.randn(100) 

N = 1000 

idx = np.random.randint(0, X.size, (N, X.size))

means = X[idx].mean(axis=1)

confint = np.percentile(means, [2.5, 97.5])

print(confint)

[-0.11865299  0.22616333]
